// *****************************************************************************
// Source code for 'JHP Menu' Add-On
// API Development Kit 22
//
// Started on 07/18/2019 at 1:13pm by CFranklin
//
// *****************************************************************************

#include "JHP_Utilities.h"

// *****************************************************************************
// Contains all the properties we need to import in XML form.
// *****************************************************************************

//NOTE! WHEN EXPORTING THE XML FROM ARCHICAD, IT WONT BE FORMATTED CORRECTLY
//1. FIND AND REPLACE ALL QUOTES (") WITH ESCAPED QUOTES (\")
//2. SELECT ALL, THEN PLACE CURSOR (SHIFT+ALT+I IN VSCODE)
//3. PLACE QUOTES AT END OF EVERY LINE (")
//4. SELECT ALL AGAIN, PLACE CURSOR, PRESS HOME TWICE TO BE AT LINE BEGINNING
//5. PLACE QUOTES AGAIN, ALL LINES SHOULD START WITH (")
//6. COPY PASTE TO HERE.

const char* JHP_GetXMLProperties(XMLPropertySet prop)
{
	const char* xmlString = "";

	switch (prop)
	{

	case XMLPropertySet::WallCheckerProperties:
	{
		//EXPORTED FROM ARCHICAD
		xmlString =
			"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>"
			"<BuildingInformation>"
			"	<PropertyDefinitionGroups>"
			"		<PropertyDefinitionGroup>"
			"			<Name>API AUDITS</Name>"
			"			<PropertyDefinitions>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Bypass</Name>"
			"					<Description>Generated by JHP_Menu plugin. Master bypass switch to remove walls from audits.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>Boolean</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Basic</DefaultValueType>"
			"						<Variant Type=\"BoolVariant\">"
			"							<Status>Normal</Status>"
			"							<Value>false</Value>"
			"						</Variant>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Bypass Angles</Name>"
			"					<Description>Generated by JHP_Menu plugin. Holds an array of angles formatted into the string for angle checking.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>String</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Basic</DefaultValueType>"
			"						<Variant Type=\"StringVariant\">"
			"							<Status>Normal</Status>"
			"							<Value/>"
			"						</Variant>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Tolerance</Name>"
			"					<Description>Generated by JHP_Menu plugin. Is always either Decimal, Standard, or Fine. </Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>String</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Basic</DefaultValueType>"
			"						<Variant Type=\"StringVariant\">"
			"							<Status>Normal</Status>"
			"							<Value>Standard</Value>"
			"						</Variant>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Is Bypass Angle</Name>"
			"					<Description>Generated by JHP_Menu plugin. Returns true if the current wall angle is within the bypass angles string array.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>Boolean</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Expression</DefaultValueType>"
			"						<ExpressionDefaultValue>"
			"							<Expression>CONTAINS ( TEXTJOIN ( \"\", TRUE, \":\", {Property:API WALLS/API Wall Angle} ), {Property:API AUDITS/API Wall Bypass Angles} )</Expression>"
			"						</ExpressionDefaultValue>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Is Orthogonal</Name>"
			"					<Description>Generated by JHP_Menu plugin. Returns true if the current wall angle is orthogonal.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>Boolean</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Expression</DefaultValueType>"
			"						<ExpressionDefaultValue>"
			"							<Expression>IF ( {Property:API WALLS/API Wall Angle} = \"0.0000\", TRUE, IF ( {Property:API WALLS/API Wall Angle} = \"90.0000\", TRUE, IF ( {Property:API WALLS/API Wall Angle} = \"180.0000\", TRUE, FALSE ) ) )</Expression>"
			"						</ExpressionDefaultValue>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"			</PropertyDefinitions>"
			"		</PropertyDefinitionGroup>"
			"		<PropertyDefinitionGroup>"
			"			<Name>API WALLS</Name>"
			"			<PropertyDefinitions>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Angle</Name>"
			"					<Description>Generated by JHP_Menu plugin. This property is set from the plugin to equal the wall angle.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>String</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Basic</DefaultValueType>"
			"						<Variant Type=\"StringVariant\">"
			"							<Status>Normal</Status>"
			"							<Value/>"
			"						</Variant>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"				<PropertyDefinition>"
			"					<Name>API Wall Length</Name>"
			"					<Description>Generated by JHP_Menu plugin. This property is set from the plugin to equal the wall angle.</Description>"
			"					<ValueDescriptor Type=\"SingleValueDescriptor\">"
			"						<ValueType>String</ValueType>"
			"					</ValueDescriptor>"
			"					<MeasureType>Default</MeasureType>"
			"					<DefaultValue>"
			"						<DefaultValueType>Basic</DefaultValueType>"
			"						<Variant Type=\"StringVariant\">"
			"							<Status>Normal</Status>"
			"							<Value/>"
			"						</Variant>"
			"					</DefaultValue>"
			"					<ClassificationIDs>"
			"						<ClassificationID>"
			"							<ItemID>Wall</ItemID>"
			"							<SystemIDName>ARCHICAD Classification</SystemIDName>"
			"							<SystemIDVersion>22</SystemIDVersion>"
			"						</ClassificationID>"
			"					</ClassificationIDs>"
			"				</PropertyDefinition>"
			"			</PropertyDefinitions>"
			"		</PropertyDefinitionGroup>"
			"	</PropertyDefinitionGroups>"
			"</BuildingInformation>";
		break;
	}

	}

	return xmlString;
}


