#ifndef _RESOURCES_HPP_
#define _RESOURCES_HPP_

#define ID_ADDON_INFO			32000
#define ID_MENU_STRINGS			32500
#define ID_MENU_PROMPT_STRINGS	32520

#define ID_MENU_ICON			32000

#endif //_RESOURCES_HPP_
